
package com.mycompany.sumsangtech;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class productFrame extends javax.swing.JFrame {
    

    private String product;
    private Double productPrice;
    
    /**
     * Creates new form productFrame
     */
    public productFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plnmain = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrderList = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnSmartphone = new javax.swing.JButton();
        btnTablet = new javax.swing.JButton();
        btnEarphone = new javax.swing.JButton();
        btnAppliance = new javax.swing.JButton();
        btnLaptop = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        txtQuantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnProduct1 = new javax.swing.JButton();
        btnProduct3 = new javax.swing.JButton();
        btnProduct4 = new javax.swing.JButton();
        btnProduct5 = new javax.swing.JButton();
        btnProduct2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        plnmain.setBackground(new java.awt.Color(102, 103, 171));

        jPanel4.setBackground(new java.awt.Color(6, 40, 61));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SUMSANG TECH POINT OF SALE SYSYTEM");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(122, 122, 122))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(6, 40, 61));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Order List");

        tblOrderList.setBackground(new java.awt.Color(0, 132, 158));
        tblOrderList.setForeground(new java.awt.Color(255, 255, 255));
        tblOrderList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblOrderList.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tblOrderList.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblOrderList);
        if (tblOrderList.getColumnModel().getColumnCount() > 0) {
            tblOrderList.getColumnModel().getColumn(0).setResizable(false);
            tblOrderList.getColumnModel().getColumn(1).setResizable(false);
            tblOrderList.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total");

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(0, 0, 0));
        txtTotal.setForeground(new java.awt.Color(255, 255, 255));
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        btnCalculate.setBackground(new java.awt.Color(0, 132, 158));
        btnCalculate.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnCalculate.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculate.setText("CALCULATE");
        btnCalculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalculateMouseClicked(evt);
            }
        });
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnConfirm.setBackground(new java.awt.Color(0, 132, 158));
        btnConfirm.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnConfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirm.setText("CONFIRM ORDER");
        btnConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmMouseClicked(evt);
            }
        });
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 132, 158));
        btnDelete.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE ORDER");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalculate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirm)
                .addGap(15, 15, 15))
        );

        jPanel6.setBackground(new java.awt.Color(6, 40, 61));

        btnSmartphone.setBackground(new java.awt.Color(155, 97, 0));
        btnSmartphone.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnSmartphone.setForeground(new java.awt.Color(255, 255, 255));
        btnSmartphone.setText("SMARTPHONE");
        btnSmartphone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSmartphoneMouseClicked(evt);
            }
        });
        btnSmartphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmartphoneActionPerformed(evt);
            }
        });

        btnTablet.setBackground(new java.awt.Color(155, 97, 0));
        btnTablet.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnTablet.setForeground(new java.awt.Color(255, 255, 255));
        btnTablet.setText("TABLET");
        btnTablet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTabletMouseClicked(evt);
            }
        });
        btnTablet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabletActionPerformed(evt);
            }
        });

        btnEarphone.setBackground(new java.awt.Color(155, 97, 0));
        btnEarphone.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnEarphone.setForeground(new java.awt.Color(255, 255, 255));
        btnEarphone.setText("EARPHONE");
        btnEarphone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEarphoneMouseClicked(evt);
            }
        });
        btnEarphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEarphoneActionPerformed(evt);
            }
        });

        btnAppliance.setBackground(new java.awt.Color(155, 97, 0));
        btnAppliance.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnAppliance.setForeground(new java.awt.Color(255, 255, 255));
        btnAppliance.setText("APPLIANCE");
        btnAppliance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnApplianceMouseClicked(evt);
            }
        });
        btnAppliance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplianceActionPerformed(evt);
            }
        });

        btnLaptop.setBackground(new java.awt.Color(155, 97, 0));
        btnLaptop.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnLaptop.setForeground(new java.awt.Color(255, 255, 255));
        btnLaptop.setText("LAPTOP");
        btnLaptop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLaptopMouseClicked(evt);
            }
        });
        btnLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaptopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSmartphone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTablet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEarphone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAppliance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLaptop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnSmartphone, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEarphone, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTablet, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAppliance, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(6, 40, 61));

        btnAdd.setBackground(new java.awt.Color(0, 132, 158));
        btnAdd.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        txtQuantity.setBackground(new java.awt.Color(0, 0, 0));
        txtQuantity.setForeground(new java.awt.Color(255, 255, 255));
        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantity");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnAdd))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(6, 40, 61));

        btnProduct1.setBackground(new java.awt.Color(0, 132, 158));
        btnProduct1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnProduct1.setForeground(new java.awt.Color(255, 255, 255));
        btnProduct1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProduct1MouseClicked(evt);
            }
        });
        btnProduct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct1ActionPerformed(evt);
            }
        });

        btnProduct3.setBackground(new java.awt.Color(0, 132, 158));
        btnProduct3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnProduct3.setForeground(new java.awt.Color(255, 255, 255));
        btnProduct3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProduct3MouseClicked(evt);
            }
        });
        btnProduct3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct3ActionPerformed(evt);
            }
        });

        btnProduct4.setBackground(new java.awt.Color(0, 132, 158));
        btnProduct4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnProduct4.setForeground(new java.awt.Color(255, 255, 255));
        btnProduct4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProduct4MouseClicked(evt);
            }
        });
        btnProduct4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct4ActionPerformed(evt);
            }
        });

        btnProduct5.setBackground(new java.awt.Color(0, 132, 158));
        btnProduct5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnProduct5.setForeground(new java.awt.Color(255, 255, 255));
        btnProduct5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProduct5MouseClicked(evt);
            }
        });
        btnProduct5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct5ActionPerformed(evt);
            }
        });

        btnProduct2.setBackground(new java.awt.Color(0, 132, 158));
        btnProduct2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnProduct2.setForeground(new java.awt.Color(255, 255, 255));
        btnProduct2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProduct2MouseClicked(evt);
            }
        });
        btnProduct2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduct2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addComponent(btnProduct5, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnProduct4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnProduct3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProduct2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProduct3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnProduct4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnProduct5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(0, 132, 158));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGOUT");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plnmainLayout = new javax.swing.GroupLayout(plnmain);
        plnmain.setLayout(plnmainLayout);
        plnmainLayout.setHorizontalGroup(
            plnmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnmainLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(plnmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plnmainLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(plnmainLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plnmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(plnmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, plnmainLayout.createSequentialGroup()
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(12, Short.MAX_VALUE))))
        );
        plnmainLayout.setVerticalGroup(
            plnmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnmainLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plnmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(plnmainLayout.createSequentialGroup()
                        .addGroup(plnmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plnmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plnmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(this, "Do want to Logout?", "Logging Out", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION){
            this.dispose();
            new loginFrame().setVisible(true);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnProduct2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProduct2ActionPerformed

    private void btnProduct2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProduct2MouseClicked
        // TODO add your handling code here:
        this.product = btnProduct2.getText();

        if (product.equals("AURORA"))
        this.productPrice = 5999.0;
        else if (product.equals("SOUND GEAR"))
        this.productPrice = 399.0;
        else if (product.equals("DUO"))
        this.productPrice = 8999.0;
        else if (product.equals("CRISP"))
        this.productPrice = 39999.0;
        else if (product.equals("CHEFT"))
        this.productPrice = 3999.0;
    }//GEN-LAST:event_btnProduct2MouseClicked

    private void btnProduct5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProduct5ActionPerformed

    private void btnProduct5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProduct5MouseClicked
        // TODO add your handling code here:
        this.product = btnProduct5.getText();
        if (product.equals("RIFT"))
        productPrice = (8999.0);
        else if (product.equals("NUTRIBUDS"))
        productPrice = 1599.0;
        else if (product.equals("MYTAB"))
        productPrice = 14999.0;
        else if (product.equals("HAWK"))
        productPrice = 69999.0;
        else if (product.equals("GALE"))
        productPrice = 1199.0;
    }//GEN-LAST:event_btnProduct5MouseClicked

    private void btnProduct4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProduct4ActionPerformed

    private void btnProduct4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProduct4MouseClicked
        // TODO add your handling code here:
        this.product = btnProduct4.getText();

        if (product.equals("FORGED"))
        productPrice = 7999.0;
        else if (product.equals("INDULGE"))
        productPrice = 599.0;
        else if (product.equals("ART"))
        productPrice = 10999.0;
        else if (product.equals("POWERED"))
        productPrice = 49999.0;
        else if (product.equals("IMMERESED"))
        productPrice = 69999.0;
    }//GEN-LAST:event_btnProduct4MouseClicked

    private void btnProduct3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProduct3ActionPerformed

    private void btnProduct3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProduct3MouseClicked
        // TODO add your handling code here:
        this.product = btnProduct3.getText();

        if (product.equals("BLACK"))
        this.productPrice = 6999.0;
        else if (product.equals("CONCERT"))
        this.productPrice = 499.0;
        else if (product.equals("CREATE"))
        this.productPrice = 9999.0;
        else if (product.equals("OVERLOAD"))
        this.productPrice = 44999.0;
        else if (product.equals("LUMOS"))
        this.productPrice = 999.0;
    }//GEN-LAST:event_btnProduct3MouseClicked

    private void btnProduct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProduct1ActionPerformed

    private void btnProduct1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProduct1MouseClicked
        // TODO add your handling code here:
        this.product = btnProduct1.getText();

        if (product.equals("NEBULA"))
        this.productPrice = 4999.0;
        else if (product.equals("MAX BASS"))
        this.productPrice = 299.0;
        else if (product.equals("HOVER"))
        this.productPrice = 7999.0;
        else if (product.equals("SWIFT"))
        this.productPrice = 34999.0;
        else if (product.equals("CLEAN"))
        this.productPrice = 14999.0;
    }//GEN-LAST:event_btnProduct1MouseClicked

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
        if (txtQuantity.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Enter quantity value");
        }
        else{
            String productprice = String.valueOf(productPrice);

            String order[] = {product, txtQuantity.getText(), productprice};

            DefaultTableModel tbl = (DefaultTableModel) tblOrderList.getModel();
            tbl.addRow(order);
            txtQuantity.setText("");
        }
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaptopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLaptopActionPerformed

    private void btnLaptopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaptopMouseClicked
        // TODO add your handling code here:
        btnProduct1.setText("SWIFT");
        btnProduct2.setText("CRISP");
        btnProduct3.setText("OVERLOAD");
        btnProduct4.setText("POWERED");
        btnProduct5.setText("HAWK");
    }//GEN-LAST:event_btnLaptopMouseClicked

    private void btnApplianceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplianceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnApplianceActionPerformed

    private void btnApplianceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApplianceMouseClicked
        // TODO add your handling code here:
        btnProduct1.setText("CLEAN");
        btnProduct2.setText("CHEFT");
        btnProduct3.setText("LUMOS");
        btnProduct4.setText("IMMERESED");
        btnProduct5.setText("GALE");
    }//GEN-LAST:event_btnApplianceMouseClicked

    private void btnEarphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEarphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEarphoneActionPerformed

    private void btnEarphoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEarphoneMouseClicked
        // TODO add your handling code here:
        btnProduct1.setText("MAX BASS");
        btnProduct2.setText("SOUND GEAR");
        btnProduct3.setText("CONCERT");
        btnProduct4.setText("INDULGE");
        btnProduct5.setText("NUTRIBUDS");
    }//GEN-LAST:event_btnEarphoneMouseClicked

    private void btnTabletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTabletActionPerformed

    private void btnTabletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTabletMouseClicked
        // TODO add your handling code here:
        btnProduct1.setText("HOVER");
        btnProduct2.setText("DUO");
        btnProduct3.setText("CREATE");
        btnProduct4.setText("ART");
        btnProduct5.setText("MYTAB");
    }//GEN-LAST:event_btnTabletMouseClicked

    private void btnSmartphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmartphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSmartphoneActionPerformed

    private void btnSmartphoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSmartphoneMouseClicked
        // TODO add your handling code here:
        btnProduct1.setText("NEBULA");
        btnProduct2.setText("AURORA");
        btnProduct3.setText("BLACK");
        btnProduct4.setText("FORGED");
        btnProduct5.setText("RIFT");
    }//GEN-LAST:event_btnSmartphoneMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tbl = (DefaultTableModel) tblOrderList.getModel();
        int index = tblOrderList.getSelectedRow();
        int reply = JOptionPane.showConfirmDialog(this, "Are you sure do you want to delete this order", "Delete Order", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION){
            tbl.removeRow(index);

            int numRow = tblOrderList.getRowCount();
            double tot = 0;

            for (int i = 0; i < numRow; i++){
                double val = Double.valueOf(tblOrderList.getValueAt(i, 2).toString());
                int quantity = Integer.valueOf(tblOrderList.getValueAt(i, 1).toString());
                tot += val* quantity;
            }
            txtTotal.setText(Double.toString(tot));
        }
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmMouseClicked
        // TODO add your handling code here:
         int numRow = tblOrderList.getRowCount();
         int reply = JOptionPane.showConfirmDialog(this, "Do you want to proceed order?", "Order Confirmation", JOptionPane.YES_NO_OPTION);
         if (reply == JOptionPane.YES_OPTION){
            DefaultTableModel tbl = (DefaultTableModel) tblOrderList.getModel();
            String recieptHeader = "---------------------------------------------------------------------------------------------------------------------"
                                               +"\n                                                      SUMSANG TECH                                         "
                                               +"\n   Address: General Luna corner Muralla Streets, Intramuros, Manila, Philippines 1002     "
                                               +"\n                                         www.facebook.com/SUMSANGTECH                                 "
                                               +"\n                                            Contact Number:+639314159265                                \n"
                                               +"---------------------------------------------------------------------------------------------------------------------"
                                               +"\nItem Name                                                                          Price\n"
                                               +"---------------------------------------------------------------------------------------------------------------------\n";
            String recieptItem = "";
            double tot =0;
            for (int i = 0; i < numRow; i++){
                double price = Double.valueOf(tblOrderList.getValueAt(i, 2).toString());
                int quantity = Integer.valueOf(tblOrderList.getValueAt(i, 1).toString());
                String item =  String.valueOf(tblOrderList.getValueAt(i, 0));
                tot += price * quantity;
                recieptItem += item + "                                                                     " + tot +"\n" 
                            + quantity + " * " + price + "\n";
            }
            String recieptFooter = "---------------------------------------------------------------------------------------------------------------------"
                                  +"\nTotal Ammount:                                                       " + tot +"\n"
                                  +"*********************************************************************************************************************" +"\n"
                                  +"                                                   THANK YOU COME AGAIN                                              " +"\n"
                                  +"*********************************************************************************************************************" +"\n"
                                  +"                                            SOFTWARE BY:SUMSANG TECH                                                 ";
            
            JOptionPane.showMessageDialog(this,recieptHeader + "\n"+  recieptItem + "\n" + recieptFooter);
            tbl.setRowCount(0);
            txtTotal.setText("");
        }
       
    }//GEN-LAST:event_btnConfirmMouseClicked

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnCalculateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalculateMouseClicked
        // TODO add your handling code here:
        int numRow = tblOrderList.getRowCount();

        double tot = 0;

        for (int i = 0; i < numRow; i++){
            double val = Double.valueOf(tblOrderList.getValueAt(i, 2).toString());
            int qunatity = Integer.valueOf(tblOrderList.getValueAt(i, 1).toString());
            tot += val* qunatity;
        }
        txtTotal.setText(Double.toString(tot));
    }//GEN-LAST:event_btnCalculateMouseClicked

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed
       /*    */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAppliance;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEarphone;
    private javax.swing.JButton btnLaptop;
    private javax.swing.JButton btnProduct1;
    private javax.swing.JButton btnProduct2;
    private javax.swing.JButton btnProduct3;
    private javax.swing.JButton btnProduct4;
    private javax.swing.JButton btnProduct5;
    private javax.swing.JButton btnSmartphone;
    private javax.swing.JButton btnTablet;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel plnmain;
    private javax.swing.JTable tblOrderList;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
